/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.26                      *
*        Compiled Aug 14 2014, 10:10:08                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: song33.c                                              *
* Font:        ·ÂËÎ                                                  *
* Height:      22                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  33                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: E:\projectV\hanzi\¿â\song33.txt                 *
* Character enabled:   0x2E (46)                                     *
* Edit/Delete/Top       at character 0x35 (53)                       *
* Edit/Delete/Top       at character 0x35 (53)                       *
* Edit/Delete/Top       at character 0x35 (53)                       *
* Edit/Delete/Top       at character 0x35 (53)                       *
* Edit/Delete/Top       at character 0x35 (53)                       *
* Edit/Delete/Top       at character 0x35 (53)                       *
* Edit/Delete/Bottom    at character 0x35 (53)                       *
* Edit/Delete/Bottom    at character 0x35 (53)                       *
* Edit/Delete/Bottom    at character 0x35 (53)                       *
* Edit/Delete/Bottom    at character 0x35 (53)                       *
* Edit/Delete/Bottom    at character 0x35 (53)                       *
* Edit/Delete/Right     at character 0x25 (37)                       *
* Save pattern file: E:\projectV\hanzi\¿â\song33.txt                 *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsong33;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsong33_0025[ 44] = { /* code 0025, PERCENT SIGN */
  __XXXX__,____X___,
  _XX__X__,___X____,
  _X___XX_,___X____,
  XX___XX_,__X_____,
  XX____X_,__X_____,
  XX____X_,__X_____,
  XX____X_,_X______,
  XX___XX_,_X______,
  _X___XX_,X_______,
  _X___XX_,X_______,
  __X_XX__,X__XX___,
  ___X___X,__XX_X__,
  _______X,_XX__XX_,
  ______X_,_XX___X_,
  ______X_,_X____X_,
  _____X__,_X____XX,
  _____X__,_X____XX,
  _____X__,_X____XX,
  ____X___,_X____X_,
  ____X___,_XX___X_,
  ___X____,__X__XX_,
  ___X____,__XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong33_002E[ 66] = { /* code 002E, FULL STOP */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ___XX___,________,________,
  __XXXX__,________,________,
  __XXXX__,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong33_0030[ 66] = { /* code 0030, DIGIT ZERO */
  _____XXX,XXX_____,________,
  ____XX__,__XX____,________,
  ___XXX__,___XX___,________,
  ___XX___,___XX___,________,
  __XXX___,____XX__,________,
  __XX____,____XX__,________,
  __XX____,____XX__,________,
  __XX____,____XX__,________,
  __XX____,____XXX_,________,
  _XXX____,____XXX_,________,
  _XXX____,____XXX_,________,
  _XXX____,____XXX_,________,
  _XXX____,____XXX_,________,
  __XX____,____XXX_,________,
  __XX____,____XX__,________,
  __XX____,____XX__,________,
  __XX____,____XX__,________,
  __XXX___,____XX__,________,
  ___XX___,___XX___,________,
  ____XX__,___XX___,________,
  ____XX__,__XX____,________,
  _____XXX,XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong33_0031[ 66] = { /* code 0031, DIGIT ONE */
  ________,X_______,________,
  ______XX,X_______,________,
  _____X_X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,XX______,________,
  ____XXXX,XXXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong33_0032[ 66] = { /* code 0032, DIGIT TWO */
  _____XXX,XXXX____,________,
  ___XX___,___XX___,________,
  ___X____,___XX___,________,
  __XX____,____XX__,________,
  __XX____,____XX__,________,
  __XXX___,____XX__,________,
  __XXX___,____XX__,________,
  ________,___XXX__,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,__XX____,________,
  ________,_XX_____,________,
  ________,XX______,________,
  _______X,X_______,________,
  ______XX,________,________,
  _____XX_,________,________,
  ____XX__,________,________,
  ____X___,_____X__,________,
  ___X____,_____X__,________,
  __X_____,____XX__,________,
  __XXXXXX,XXXXXX__,________,
  __XXXXXX,XXXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong33_0033[ 66] = { /* code 0033, DIGIT THREE */
  _____XXX,XXX_____,________,
  ___XX___,__XX____,________,
  ___X____,___XX___,________,
  __XX____,___XX___,________,
  __XXX___,___XX___,________,
  ___XX___,___XX___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,__XX____,________,
  ________,XXX_____,________,
  ______XX,XXX_____,________,
  ________,__XX____,________,
  ________,___XX___,________,
  ________,____XX__,________,
  ________,____XX__,________,
  ________,____XX__,________,
  __XX____,____XX__,________,
  __XXX___,____XX__,________,
  __XXX___,____XX__,________,
  __XX____,___XX___,________,
  ___XX___,__XX____,________,
  ____XXXX,XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong33_0034[ 66] = { /* code 0034, DIGIT FOUR */
  ________,__XX____,________,
  ________,_XXX____,________,
  ________,_XXX____,________,
  ________,X_XX____,________,
  _______X,X_XX____,________,
  _______X,__XX____,________,
  ______X_,__XX____,________,
  ______X_,__XX____,________,
  _____X__,__XX____,________,
  ____X___,__XX____,________,
  ____X___,__XX____,________,
  ___X____,__XX____,________,
  __X_____,__XX____,________,
  __X_____,__XX____,________,
  _X______,__XX____,________,
  __XXXXXX,XXXXXX__,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,_XXX____,________,
  ______XX,XXXXXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong33_0035[ 66] = { /* code 0035, DIGIT FIVE */
  ___XXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXX__,________,
  ___X____,________,________,
  ___X____,________,________,
  ___X____,________,________,
  ___X____,________,________,
  ___X____,________,________,
  ___X____,________,________,
  ___X__XX,XXX_____,________,
  ___XXX__,__XXX___,________,
  ___XX___,___XX___,________,
  ___X____,____XX__,________,
  ________,____XX__,________,
  ________,____XX__,________,
  ________,____XX__,________,
  ________,____XX__,________,
  __XXX___,____XX__,________,
  __XXX___,____XX__,________,
  __XX____,____XX__,________,
  __XX____,___XX___,________,
  ___XX___,__XX____,________,
  _____XXX,XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong33_0036[ 66] = { /* code 0036, DIGIT SIX */
  ______XX,XXXX____,________,
  _____XX_,___XX___,________,
  ____X___,___XXX__,________,
  ___XX___,___XX___,________,
  ___XX___,________,________,
  __XX____,________,________,
  __XX____,________,________,
  __XX____,________,________,
  __XX___X,XXXX____,________,
  __XX_XX_,__XXX___,________,
  _XXXXX__,___XXX__,________,
  _XXXX___,____XX__,________,
  _XXX____,____XX__,________,
  _XXX____,____XXX_,________,
  __XX____,____XXX_,________,
  __XX____,____XXX_,________,
  __XX____,____XXX_,________,
  __XX____,____XX__,________,
  ___XX___,____XX__,________,
  ___XX___,____XX__,________,
  ____XX__,___XX___,________,
  _____XXX,XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong33_0037[ 66] = { /* code 0037, DIGIT SEVEN */
  ___XXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXX__,________,
  __XX____,____X___,________,
  __X_____,____X___,________,
  __X_____,___X____,________,
  ________,___X____,________,
  ________,__X_____,________,
  ________,__X_____,________,
  ________,_X______,________,
  ________,_X______,________,
  ________,XX______,________,
  ________,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  ______XX,X_______,________,
  ______XX,X_______,________,
  ______XX,X_______,________,
  ______XX,X_______,________,
  ______XX,X_______,________,
  ______XX,X_______,________,
  ______XX,X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong33_0038[ 66] = { /* code 0038, DIGIT EIGHT */
  _____XXX,XXX_____,________,
  ___XX___,___XX___,________,
  __XX____,____XX__,________,
  __XX____,____XX__,________,
  __XX____,____XX__,________,
  __XX____,____XX__,________,
  __XX____,____XX__,________,
  __XXX___,____X___,________,
  ___XXXX_,___XX___,________,
  ____XXXX,X_XX____,________,
  _____XXX,XXX_____,________,
  ____X___,XXXX____,________,
  ___X____,__XXX___,________,
  __XX____,___XXX__,________,
  __X_____,____XX__,________,
  _XX_____,____XX__,________,
  _XX_____,____XX__,________,
  _XX_____,____XX__,________,
  __X_____,____XX__,________,
  __XX____,____XX__,________,
  ___XX___,___XX___,________,
  _____XXX,XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong33_0039[ 66] = { /* code 0039, DIGIT NINE */
  ____XXXX,XXX_____,________,
  ___XX___,__XX____,________,
  __XX____,___XX___,________,
  __XX____,____X___,________,
  __XX____,____XX__,________,
  _XXX____,____XX__,________,
  _XX_____,____XX__,________,
  _XXX____,____XX__,________,
  _XXX____,____XXX_,________,
  __XX____,____XXX_,________,
  __XX____,___XXXX_,________,
  __XXX___,__X_XXX_,________,
  ___XXXX_,XX__XX__,________,
  _____XXX,X___XX__,________,
  ________,____XX__,________,
  ________,____XX__,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ___XX___,___XX___,________,
  __XXX___,__XX____,________,
  ___XX___,_XX_____,________,
  ____XXXX,XX______,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontsong33_CharInfo[12] = {
   {  16,  16,  2, acGUI_Fontsong33_0025 } /* code 0025 */
  ,{  17,  17,  3, acGUI_Fontsong33_002E } /* code 002E */
  ,{  17,  17,  3, acGUI_Fontsong33_0030 } /* code 0030 */
  ,{  17,  17,  3, acGUI_Fontsong33_0031 } /* code 0031 */
  ,{  17,  17,  3, acGUI_Fontsong33_0032 } /* code 0032 */
  ,{  17,  17,  3, acGUI_Fontsong33_0033 } /* code 0033 */
  ,{  17,  17,  3, acGUI_Fontsong33_0034 } /* code 0034 */
  ,{  17,  17,  3, acGUI_Fontsong33_0035 } /* code 0035 */
  ,{  17,  17,  3, acGUI_Fontsong33_0036 } /* code 0036 */
  ,{  17,  17,  3, acGUI_Fontsong33_0037 } /* code 0037 */
  ,{  17,  17,  3, acGUI_Fontsong33_0038 } /* code 0038 */
  ,{  17,  17,  3, acGUI_Fontsong33_0039 } /* code 0039 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong33_Prop3 = {
   0x0030 /* first character */
  ,0x0039 /* last character  */
  ,&GUI_Fontsong33_CharInfo[  2] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong33_Prop2 = {
   0x002E /* first character */
  ,0x002E /* last character  */
  ,&GUI_Fontsong33_CharInfo[  1] /* address of first character */
  ,&GUI_Fontsong33_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong33_Prop1 = {
   0x0025 /* first character */
  ,0x0025 /* last character  */
  ,&GUI_Fontsong33_CharInfo[  0] /* address of first character */
  ,&GUI_Fontsong33_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontsong33 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,22 /* height of font  */
  ,22 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontsong33_Prop1}
  ,22 /* Baseline */
  ,15 /* Height of lowercase characters */
  ,22 /* Height of capital characters */
};

