/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.26                      *
*        Compiled Aug 14 2014, 10:10:08                              *
*                                                                    *
*        (c) 1998 - 2014 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: song64.c                                              *
* Font:        ·ÂËÎ                                                  *
* Height:      43                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  64                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: E:\projectV\hanzi\¿â\song64.txt                 *
* Edit/Delete/Bottom    at character 0x39 (57)                       *
* Edit/Delete/Bottom    at character 0x39 (57)                       *
* Edit/Delete/Bottom    at character 0x39 (57)                       *
* Edit/Delete/Bottom    at character 0x39 (57)                       *
* Edit/Delete/Bottom    at character 0x39 (57)                       *
* Edit/Delete/Bottom    at character 0x39 (57)                       *
* Edit/Delete/Bottom    at character 0x39 (57)                       *
* Edit/Delete/Bottom    at character 0x39 (57)                       *
* Edit/Delete/Bottom    at character 0x39 (57)                       *
* Edit/Delete/Top       at character 0x39 (57)                       *
* Edit/Delete/Top       at character 0x39 (57)                       *
* Edit/Delete/Top       at character 0x39 (57)                       *
* Edit/Delete/Top       at character 0x39 (57)                       *
* Edit/Delete/Top       at character 0x39 (57)                       *
* Edit/Delete/Top       at character 0x39 (57)                       *
* Edit/Delete/Top       at character 0x39 (57)                       *
* Edit/Delete/Top       at character 0x39 (57)                       *
* Edit/Delete/Top       at character 0x39 (57)                       *
* Edit/Delete/Top       at character 0x39 (57)                       *
* Edit/Delete/Top       at character 0x39 (57)                       *
* Edit/Delete/Top       at character 0x39 (57)                       *
* Pixel index of character 0x2C (44) at 13/42 set to 0               *
* Pixel index of character 0x2C (44) at 14/41 set to 0               *
* Pixel index of character 0x2C (44) at 14/42 set to 0               *
* Pixel index of character 0x2C (44) at 15/42 set to 0               *
* Pixel index of character 0x2C (44) at 16/41 set to 0               *
* Pixel index of character 0x2C (44) at 15/41 set to 0               *
* Pixel index of character 0x2C (44) at 13/41 set to 0               *
* Pixel index of character 0x2C (44) at 12/42 set to 1               *
* Pixel index of character 0x2C (44) at 11/41 set to 0               *
* Pixel index of character 0x2C (44) at 11/41 set to 1               *
* Pixel index of character 0x2C (44) at 12/41 set to 0               *
* Pixel index of character 0x2C (44) at 12/42 set to 0               *
* Pixel index of character 0x2C (44) at 11/41 set to 0               *
* Pixel index of character 0x2C (44) at 17/40 set to 1               *
* Pixel index of character 0x2C (44) at 10/41 set to 0               *
* Pixel index of character 0x2C (44) at 10/40 set to 0               *
* Pixel index of character 0x2C (44) at 14/40 set to 0               *
* Pixel index of character 0x2C (44) at 12/40 set to 0               *
* Pixel index of character 0x2C (44) at 13/40 set to 0               *
* Pixel index of character 0x2C (44) at 15/40 set to 0               *
* Pixel index of character 0x2C (44) at 16/40 set to 0               *
* Pixel index of character 0x2C (44) at 17/40 set to 0               *
* Pixel index of character 0x2C (44) at 11/40 set to 0               *
* Pixel index of character 0x2C (44) at 12/39 set to 0               *
* Pixel index of character 0x2C (44) at 10/39 set to 0               *
* Pixel index of character 0x2C (44) at 13/39 set to 0               *
* Pixel index of character 0x2C (44) at 14/39 set to 0               *
* Pixel index of character 0x2C (44) at 15/39 set to 0               *
* Pixel index of character 0x2C (44) at 16/39 set to 0               *
* Pixel index of character 0x2C (44) at 16/38 set to 0               *
* Pixel index of character 0x2C (44) at 10/39 set to 1               *
* Pixel index of character 0x2C (44) at 8/40 set to 1                *
* Pixel index of character 0x2C (44) at 8/39 set to 1                *
* Pixel index of character 0x2C (44) at 7/41 set to 1                *
* Pixel index of character 0x2C (44) at 7/42 set to 1                *
* Pixel index of character 0x2C (44) at 8/42 set to 1                *
* Pixel index of character 0x2C (44) at 8/41 set to 1                *
* Pixel index of character 0x2C (44) at 9/41 set to 1                *
* Pixel index of character 0x2C (44) at 10/40 set to 1               *
* Pixel index of character 0x2C (44) at 9/40 set to 1                *
* Pixel index of character 0x2C (44) at 10/41 set to 1               *
* Pixel index of character 0x2C (44) at 11/40 set to 1               *
* Pixel index of character 0x2C (44) at 12/39 set to 1               *
* Pixel index of character 0x2C (44) at 13/39 set to 1               *
* Pixel index of character 0x2C (44) at 15/38 set to 0               *
* Pixel index of character 0x2C (44) at 11/35 set to 1               *
* Pixel index of character 0x2C (44) at 9/37 set to 1                *
* Pixel index of character 0x2C (44) at 13/35 set to 1               *
* Pixel index of character 0x2C (44) at 13/34 set to 1               *
* Pixel index of character 0x2C (44) at 12/34 set to 1               *
* Pixel index of character 0x2C (44) at 14/34 set to 1               *
* Pixel index of character 0x2C (44) at 15/34 set to 1               *
* Pixel index of character 0x2C (44) at 16/34 set to 1               *
* Pixel index of character 0x2C (44) at 16/35 set to 1               *
* Pixel index of character 0x2C (44) at 16/36 set to 1               *
* Pixel index of character 0x2C (44) at 14/35 set to 1               *
* Pixel index of character 0x2C (44) at 15/35 set to 1               *
* Pixel index of character 0x2C (44) at 6/42 set to 1                *
* Pixel index of character 0x2C (44) at 6/41 set to 1                *
* Read pattern file: E:\projectV\hanzi\¿â\song64_1.txt               *
* Save pattern file: E:\projectV\hanzi\¿â\song64_1.txt               *
* Pixel index of character 0x2C (44) at 7/40 set to 1                *
* Pixel index of character 0x2C (44) at 8/38 set to 1                *
* Pixel index of character 0x2C (44) at 8/37 set to 1                *
* Pixel index of character 0x2C (44) at 9/36 set to 1                *
* Pixel index of character 0x2C (44) at 9/35 set to 1                *
* Pixel index of character 0x2C (44) at 10/35 set to 1               *
* Pixel index of character 0x2C (44) at 10/34 set to 1               *
* Pixel index of character 0x2C (44) at 9/34 set to 1                *
* Pixel index of character 0x2C (44) at 11/34 set to 1               *
* Pixel index of character 0x2C (44) at 10/33 set to 1               *
* Pixel index of character 0x2C (44) at 16/36 set to 0               *
* Pixel index of character 0x2C (44) at 16/35 set to 0               *
* Pixel index of character 0x2C (44) at 16/34 set to 0               *
* Pixel index of character 0x2C (44) at 15/37 set to 0               *
* Pixel index of character 0x2C (44) at 14/38 set to 0               *
* Pixel index of character 0x2C (44) at 13/39 set to 0               *
* Pixel index of character 0x2C (44) at 11/33 set to 1               *
* Pixel index of character 0x2C (44) at 12/33 set to 1               *
* Pixel index of character 0x2C (44) at 13/33 set to 1               *
* Pixel index of character 0x2C (44) at 14/33 set to 1               *
* Pixel index of character 0x2C (44) at 11/32 set to 1               *
* Pixel index of character 0x2C (44) at 12/32 set to 1               *
* Pixel index of character 0x2C (44) at 13/32 set to 1               *
* Pixel index of character 0x2C (44) at 14/32 set to 1               *
* Pixel index of character 0x2C (44) at 15/33 set to 1               *
* Save pattern file: E:\projectV\hanzi\¿â\song64_1.txt               *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Fontsong64;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_Fontsong64_002C[172] = { /* code 002C, COMMA */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,___XXXX_,________,________,
  ________,__XXXXXX,________,________,
  ________,_XXXXXXX,________,________,
  ________,_XXXXXXX,________,________,
  ________,_XXXXXXX,________,________,
  ________,XXXXXXX_,________,________,
  ________,XXXXXX__,________,________,
  ________,XXXXX___,________,________,
  _______X,XXXX____,________,________,
  ______XX,XXX_____,________,________,
  ______XX,X_______,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong64_0030[172] = { /* code 0030, DIGIT ZERO */
  ________,____XXXX,XXX_____,________,
  ________,__XXXXXX,XXXXX___,________,
  ________,_XXXX___,__XXXX__,________,
  ________,XXXX____,____XXX_,________,
  _______X,XXX_____,____XXXX,________,
  _______X,XXX_____,_____XXX,X_______,
  ______XX,XX______,______XX,X_______,
  _____XXX,XX______,______XX,XX______,
  _____XXX,X_______,______XX,XX______,
  _____XXX,X_______,______XX,XXX_____,
  ____XXXX,X_______,_______X,XXX_____,
  ____XXXX,________,_______X,XXX_____,
  ____XXXX,________,_______X,XXXX____,
  ___XXXXX,________,_______X,XXXX____,
  ___XXXXX,________,_______X,XXXX____,
  ___XXXXX,________,_______X,XXXX____,
  ___XXXXX,________,________,XXXX____,
  ___XXXXX,________,________,XXXX____,
  ___XXXXX,________,________,XXXX____,
  ___XXXXX,________,________,XXXX____,
  ___XXXXX,________,________,XXXX____,
  ___XXXXX,________,________,XXXXX___,
  ___XXXXX,________,________,XXXX____,
  ___XXXXX,________,________,XXXX____,
  ___XXXXX,________,________,XXXX____,
  ___XXXXX,________,________,XXXX____,
  ___XXXXX,________,________,XXXX____,
  ___XXXXX,________,________,XXXX____,
  ___XXXXX,________,_______X,XXXX____,
  ___XXXXX,________,_______X,XXXX____,
  ____XXXX,________,_______X,XXXX____,
  ____XXXX,________,_______X,XXX_____,
  ____XXXX,X_______,_______X,XXX_____,
  ____XXXX,X_______,_______X,XXX_____,
  _____XXX,X_______,______XX,XX______,
  _____XXX,XX______,______XX,XX______,
  ______XX,XX______,______XX,XX______,
  ______XX,XX______,_____XXX,X_______,
  _______X,XXX_____,____XXXX,________,
  ________,XXXX____,____XXXX,________,
  ________,_XXXX___,___XXXX_,________,
  ________,__XXXXXX,XXXXXX__,________,
  ________,___XXXXX,XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong64_0031[172] = { /* code 0031, DIGIT ONE */
  ________,________,XX______,________,
  ________,________,XX______,________,
  ________,______XX,XX______,________,
  _______X,XXXXXXXX,XX______,________,
  _______X,XXXXXXXX,XX______,________,
  ________,_____XXX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,XX______,________,
  ________,_____XXX,XXX_____,________,
  _______X,XXXXXXXX,XXXXXXXX,X_______,
  _______X,XXXXXXXX,XXXXXXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong64_0032[172] = { /* code 0032, DIGIT TWO */
  ________,___XXXXX,XXXXX___,________,
  ________,_XXXXXXX,XXXXXXX_,________,
  _______X,XXX_____,___XXXXX,________,
  ______XX,X_______,_____XXX,X_______,
  _____XXX,X_______,_____XXX,XX______,
  _____XXX,________,______XX,XX______,
  ____XXXX,________,______XX,XXX_____,
  ____XXXX,________,_______X,XXX_____,
  ____XXXX,________,_______X,XXX_____,
  ____XXXX,________,_______X,XXX_____,
  ____XXXX,X_______,_______X,XXX_____,
  ____XXXX,X_______,_______X,XXX_____,
  ____XXXX,X_______,_______X,XXX_____,
  _____XXX,X_______,_______X,XXX_____,
  ________,________,______XX,XXX_____,
  ________,________,______XX,XX______,
  ________,________,______XX,XX______,
  ________,________,_____XXX,X_______,
  ________,________,_____XXX,X_______,
  ________,________,____XXXX,________,
  ________,________,___XXXX_,________,
  ________,________,___XXX__,________,
  ________,________,__XXX___,________,
  ________,________,_XXX____,________,
  ________,________,XXX_____,________,
  ________,_______X,XX______,________,
  ________,______XX,X_______,________,
  ________,_____XXX,________,________,
  ________,____XXX_,________,________,
  ________,___XXX__,________,________,
  ________,__XXX___,________,________,
  ________,_XXX____,________,________,
  ________,XXX_____,________,__XX____,
  ________,XX______,________,__XX____,
  _______X,X_______,________,__X_____,
  ______XX,X_______,________,_XX_____,
  _____XXX,________,________,_XX_____,
  ____XXX_,________,________,XXX_____,
  ____XX__,________,_______X,XXX_____,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong64_0033[172] = { /* code 0033, DIGIT THREE */
  ________,___XXXXX,XXX_____,________,
  ________,XXXXXXXX,XXXXX___,________,
  _______X,XX______,__XXXXX_,________,
  ______XX,X_______,___XXXXX,________,
  _____XXX,________,____XXXX,________,
  _____XXX,________,_____XXX,X_______,
  ____XXXX,________,_____XXX,X_______,
  ____XXXX,X_______,_____XXX,XX______,
  ____XXXX,X_______,______XX,XX______,
  ____XXXX,X_______,______XX,XX______,
  _____XXX,X_______,______XX,XX______,
  ______XX,________,______XX,XX______,
  ________,________,______XX,XX______,
  ________,________,_____XXX,X_______,
  ________,________,_____XXX,X_______,
  ________,________,____XXXX,________,
  ________,________,____XXXX,________,
  ________,________,___XXXX_,________,
  ________,________,_XXXX___,________,
  ________,____XXXX,XXX_____,________,
  ________,____XXXX,XXXX____,________,
  ________,________,_XXXXX__,________,
  ________,________,___XXXX_,________,
  ________,________,_____XXX,X_______,
  ________,________,_____XXX,X_______,
  ________,________,______XX,XX______,
  ________,________,_______X,XXX_____,
  ________,________,_______X,XXX_____,
  ________,________,_______X,XXX_____,
  ________,________,_______X,XXXX____,
  ________,________,_______X,XXXX____,
  ______X_,________,_______X,XXXX____,
  _____XXX,X_______,_______X,XXXX____,
  ____XXXX,X_______,_______X,XXXX____,
  ____XXXX,X_______,_______X,XXX_____,
  ____XXXX,X_______,_______X,XXX_____,
  ____XXXX,X_______,______XX,XXX_____,
  ____XXXX,________,______XX,XX______,
  ____XXXX,________,_____XXX,X_______,
  _____XXX,X_______,_____XXX,X_______,
  ______XX,XX______,___XXXXX,________,
  _______X,XXXX____,_XXXXX__,________,
  ________,_XXXXXXX,XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong64_0034[172] = { /* code 0034, DIGIT FOUR */
  ________,________,____XXX_,________,
  ________,________,___XXXX_,________,
  ________,________,___XXXX_,________,
  ________,________,__XXXXX_,________,
  ________,________,_XXXXXX_,________,
  ________,________,_XXXXXX_,________,
  ________,________,XX_XXXX_,________,
  ________,_______X,XX_XXXX_,________,
  ________,_______X,X__XXXX_,________,
  ________,______XX,___XXXX_,________,
  ________,_____XXX,___XXXX_,________,
  ________,_____XX_,___XXXX_,________,
  ________,____XX__,___XXXX_,________,
  ________,____XX__,___XXXX_,________,
  ________,___XX___,___XXXX_,________,
  ________,__XX____,___XXXX_,________,
  ________,__XX____,___XXXX_,________,
  ________,_XX_____,___XXXX_,________,
  ________,XXX_____,___XXXX_,________,
  ________,XX______,___XXXX_,________,
  _______X,X_______,___XXXX_,________,
  _______X,X_______,___XXXX_,________,
  ______XX,________,___XXXX_,________,
  _____XX_,________,___XXXX_,________,
  _____XX_,________,___XXXX_,________,
  ____XX__,________,___XXXX_,________,
  ___XXX__,________,___XXXX_,________,
  ___XX___,________,___XXXX_,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  ________,________,___XXXX_,________,
  ________,________,___XXXX_,________,
  ________,________,___XXXX_,________,
  ________,________,___XXXX_,________,
  ________,________,___XXXX_,________,
  ________,________,___XXXX_,________,
  ________,________,___XXXX_,________,
  ________,________,___XXXX_,________,
  ________,________,___XXXX_,________,
  ________,________,___XXXX_,________,
  ________,________,__XXXXX_,________,
  ________,____XXXX,XXXXXXXX,XXXXX___,
  ________,____XXXX,XXXXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong64_0035[172] = { /* code 0035, DIGIT FIVE */
  ______XX,XXXXXXXX,XXXXXXXX,XXX_____,
  ______XX,XXXXXXXX,XXXXXXXX,XXX_____,
  ______XX,XXXXXXXX,XXXXXXXX,XXX_____,
  ______XX,XXXXXXXX,XXXXXXXX,XX______,
  ______XX,________,________,________,
  ______XX,________,________,________,
  ______XX,________,________,________,
  ______XX,________,________,________,
  ______XX,________,________,________,
  ______XX,________,________,________,
  ______XX,________,________,________,
  ______XX,________,________,________,
  ______XX,________,________,________,
  ______XX,________,________,________,
  ______XX,________,________,________,
  ______XX,________,________,________,
  ______X_,___XXXXX,XXXXXX__,________,
  ______X_,__XXXXXX,XXXXXXX_,________,
  _____XX_,_XXX____,___XXXXX,________,
  _____XX_,XX______,____XXXX,X_______,
  _____XXX,X_______,_____XXX,XX______,
  _____XXX,X_______,______XX,XX______,
  _____XXX,________,______XX,XXX_____,
  ________,________,_______X,XXX_____,
  ________,________,_______X,XXX_____,
  ________,________,_______X,XXXX____,
  ________,________,_______X,XXXX____,
  ________,________,_______X,XXXX____,
  ________,________,_______X,XXXX____,
  ________,________,_______X,XXXX____,
  ________,________,_______X,XXXX____,
  _____XXX,X_______,_______X,XXXX____,
  ____XXXX,X_______,_______X,XXX_____,
  ____XXXX,X_______,_______X,XXX_____,
  ___XXXXX,X_______,_______X,XXX_____,
  ____XXXX,X_______,_______X,XXX_____,
  ____XXXX,________,______XX,XX______,
  ____XXXX,________,______XX,XX______,
  _____XXX,________,_____XXX,X_______,
  _____XXX,________,_____XXX,X_______,
  _______X,XX______,___XXXXX,________,
  ________,XXXXX___,_XXXXXX_,________,
  ________,__XXXXXX,XXXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong64_0036[172] = { /* code 0036, DIGIT SIX */
  ________,______XX,XXXXXX__,________,
  ________,____XXXX,XXXXXXXX,________,
  ________,__XXXX__,_____XXX,X_______,
  ________,_XXX____,_____XXX,XX______,
  ________,XXX_____,_____XXX,XX______,
  _______X,XX______,_____XXX,XX______,
  _______X,XX______,_____XXX,XX______,
  ______XX,X_______,______XX,XX______,
  _____XXX,X_______,________,________,
  _____XXX,X_______,________,________,
  _____XXX,________,________,________,
  ____XXXX,________,________,________,
  ____XXXX,________,________,________,
  ____XXXX,________,________,________,
  ____XXXX,________,________,________,
  ___XXXXX,________,________,________,
  ___XXXXX,_____XXX,XXXXXX__,________,
  ___XXXXX,___XXXXX,XXXXXXXX,________,
  ___XXXXX,__XXXXX_,___XXXXX,X_______,
  ___XXXXX,_XXX____,_____XXX,XX______,
  ___XXXXX,XXX_____,______XX,XX______,
  ___XXXXX,XX______,______XX,XXX_____,
  ___XXXXX,X_______,_______X,XXX_____,
  ___XXXXX,X_______,_______X,XXXX____,
  ___XXXXX,________,________,XXXX____,
  ___XXXXX,________,________,XXXX____,
  ___XXXXX,________,________,XXXX____,
  ___XXXXX,________,________,XXXX____,
  ___XXXXX,________,________,XXXX____,
  ___XXXXX,________,________,XXXX____,
  ___XXXXX,________,________,XXXX____,
  ___XXXXX,________,________,XXXX____,
  ____XXXX,________,________,XXXX____,
  ____XXXX,________,________,XXXX____,
  ____XXXX,X_______,________,XXXX____,
  _____XXX,X_______,________,XXXX____,
  _____XXX,X_______,_______X,XXX_____,
  ______XX,XX______,_______X,XXX_____,
  ______XX,XXX_____,_______X,XX______,
  _______X,XXXX____,______XX,X_______,
  ________,XXXXX___,_____XXX,________,
  ________,_XXXXXX_,___XXXX_,________,
  ________,___XXXXX,XXXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong64_0037[172] = { /* code 0037, DIGIT SEVEN */
  _____XXX,XXXXXXXX,XXXXXXXX,XXXX____,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXX____,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXX____,
  _____XXX,XXXXXXXX,XXXXXXXX,XXX_____,
  _____XXX,X_______,________,XX______,
  _____XXX,________,________,XX______,
  ____XXX_,________,_______X,X_______,
  ____XX__,________,_______X,X_______,
  ____XX__,________,______XX,________,
  ____XX__,________,______XX,________,
  ____X___,________,_____XX_,________,
  ________,________,____XXX_,________,
  ________,________,____XX__,________,
  ________,________,___XXX__,________,
  ________,________,___XX___,________,
  ________,________,__XXX___,________,
  ________,________,__XX____,________,
  ________,________,_XXX____,________,
  ________,________,_XXX____,________,
  ________,________,XXX_____,________,
  ________,________,XXX_____,________,
  ________,________,XXX_____,________,
  ________,_______X,XX______,________,
  ________,_______X,XX______,________,
  ________,______XX,XX______,________,
  ________,______XX,X_______,________,
  ________,______XX,X_______,________,
  ________,_____XXX,X_______,________,
  ________,_____XXX,X_______,________,
  ________,_____XXX,X_______,________,
  ________,____XXXX,X_______,________,
  ________,____XXXX,X_______,________,
  ________,____XXXX,X_______,________,
  ________,____XXXX,X_______,________,
  ________,___XXXXX,X_______,________,
  ________,___XXXXX,X_______,________,
  ________,___XXXXX,X_______,________,
  ________,___XXXXX,X_______,________,
  ________,___XXXXX,X_______,________,
  ________,___XXXXX,X_______,________,
  ________,___XXXXX,X_______,________,
  ________,___XXXXX,X_______,________,
  ________,____XXXX,________,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong64_0038[172] = { /* code 0038, DIGIT EIGHT */
  ________,___XXXXX,XXXX____,________,
  ________,XXXXXXXX,XXXXXXX_,________,
  _______X,XXX_____,____XXXX,________,
  ______XX,X_______,_____XXX,X_______,
  _____XXX,X_______,______XX,XX______,
  _____XXX,________,_______X,XX______,
  ____XXXX,________,_______X,XXX_____,
  ____XXX_,________,________,XXX_____,
  ____XXX_,________,________,XXX_____,
  ____XXX_,________,________,XXX_____,
  ____XXX_,________,________,XXX_____,
  ____XXX_,________,________,XXX_____,
  ____XXXX,________,________,XXX_____,
  ____XXXX,X_______,_______X,XXX_____,
  _____XXX,XX______,_______X,XX______,
  _____XXX,XXX_____,______XX,XX______,
  ______XX,XXXX____,______XX,X_______,
  _______X,XXXXXX__,_____XXX,________,
  ________,XXXXXXXX,___XXXX_,________,
  ________,_XXXXXXX,XXXXX___,________,
  ________,__XXXXXX,XXXX____,________,
  ________,_XXX_XXX,XXXXXX__,________,
  _______X,XXX____X,XXXXXXX_,________,
  ______XX,XX______,_XXXXXXX,________,
  _____XXX,X_______,__XXXXXX,X_______,
  _____XXX,________,____XXXX,XX______,
  ____XXX_,________,_____XXX,XX______,
  ____XXX_,________,______XX,XXX_____,
  ___XXXX_,________,_______X,XXX_____,
  ___XXX__,________,_______X,XXXX____,
  ___XXX__,________,________,XXXX____,
  ___XXX__,________,________,XXXX____,
  ___XXX__,________,________,XXXX____,
  ___XXX__,________,________,XXXX____,
  ___XXX__,________,________,XXXX____,
  ___XXX__,________,________,XXXX____,
  ___XXXX_,________,________,XXX_____,
  ____XXX_,________,_______X,XXX_____,
  _____XXX,________,_______X,XX______,
  _____XXX,X_______,______XX,X_______,
  _______X,XX______,_____XXX,________,
  ________,XXXXX___,__XXXXX_,________,
  ________,__XXXXXX,XXXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_Fontsong64_0039[172] = { /* code 0039, DIGIT NINE */
  ________,__XXXXXX,XXX_____,________,
  ________,XXXXXXXX,XXXXX___,________,
  _______X,XXX_____,___XXXX_,________,
  ______XX,XX______,____XXXX,________,
  _____XXX,X_______,_____XXX,X_______,
  _____XXX,________,______XX,X_______,
  ____XXXX,________,______XX,XX______,
  ____XXXX,________,_______X,XX______,
  ___XXXX_,________,_______X,XXX_____,
  ___XXXX_,________,_______X,XXX_____,
  ___XXXX_,________,_______X,XXX_____,
  ___XXXX_,________,_______X,XXXX____,
  ___XXXX_,________,_______X,XXXX____,
  ___XXXX_,________,_______X,XXXX____,
  ___XXXX_,________,_______X,XXXX____,
  ___XXXX_,________,_______X,XXXX____,
  ___XXXX_,________,_______X,XXXX____,
  ___XXXX_,________,_______X,XXXX____,
  ___XXXX_,________,_______X,XXXX____,
  ___XXXXX,________,______XX,XXXX____,
  ___XXXXX,________,_____XXX,XXXX____,
  ____XXXX,X_______,_____XXX,XXXX____,
  ____XXXX,X_______,____XX_X,XXXX____,
  _____XXX,XX______,__XXX__X,XXXX____,
  ______XX,XXXX____,XXXX___X,XXXX____,
  ________,XXXXXXXX,XXX____X,XXXX____,
  ________,__XXXXXX,X______X,XXXX____,
  ________,________,_______X,XXXX____,
  ________,________,_______X,XXX_____,
  ________,________,_______X,XXX_____,
  ________,________,______XX,XXX_____,
  ________,________,______XX,XX______,
  ________,________,______XX,XX______,
  ________,________,______XX,XX______,
  ________,________,_____XXX,X_______,
  ______XX,X_______,_____XXX,X_______,
  _____XXX,XX______,____XXXX,________,
  _____XXX,XX______,____XXXX,________,
  _____XXX,XX______,___XXXX_,________,
  _____XXX,XX______,__XXXX__,________,
  ______XX,XX______,_XXXX___,________,
  ______XX,XXX____X,XXXX____,________,
  ________,XXXXXXXX,XX______,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_Fontsong64_CharInfo[11] = {
   {  32,  32,  4, acGUI_Fontsong64_002C } /* code 002C */
  ,{  32,  32,  4, acGUI_Fontsong64_0030 } /* code 0030 */
  ,{  32,  32,  4, acGUI_Fontsong64_0031 } /* code 0031 */
  ,{  32,  32,  4, acGUI_Fontsong64_0032 } /* code 0032 */
  ,{  32,  32,  4, acGUI_Fontsong64_0033 } /* code 0033 */
  ,{  32,  32,  4, acGUI_Fontsong64_0034 } /* code 0034 */
  ,{  32,  32,  4, acGUI_Fontsong64_0035 } /* code 0035 */
  ,{  32,  32,  4, acGUI_Fontsong64_0036 } /* code 0036 */
  ,{  32,  32,  4, acGUI_Fontsong64_0037 } /* code 0037 */
  ,{  32,  32,  4, acGUI_Fontsong64_0038 } /* code 0038 */
  ,{  32,  32,  4, acGUI_Fontsong64_0039 } /* code 0039 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong64_Prop2 = {
   0x0030 /* first character */
  ,0x0039 /* last character  */
  ,&GUI_Fontsong64_CharInfo[  1] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_Fontsong64_Prop1 = {
   0x002C /* first character */
  ,0x002C /* last character  */
  ,&GUI_Fontsong64_CharInfo[  0] /* address of first character */
  ,&GUI_Fontsong64_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_Fontsong64 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,43 /* height of font  */
  ,43 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_Fontsong64_Prop1}
  ,43 /* Baseline */
  ,16 /* Height of lowercase characters */
  ,43 /* Height of capital characters */
};

